### ISSUE TITLE
Room title name bug

### ISSUE THREAD

**Issue by Goutam363** [jonathanD27868/chat-app-1#3]
When a new user creates another room or join, the room title of every window gets updated to the room name of the last joined room.

**Comment by jonathanD27868** [comment]
Hi,
Thank you for your message I didn't notice that !
I've made a simple change in the front side in chat.js. For sure it'd be better and more efficient to use socket.io rooms to only send messages to specific subsets but it's not an app intended for production so I keep it simple ^^
